### ISSUE TITLE
no tags for versions

### ISSUE THREAD

**Issue by greenpau** [nuagenetworks/nuage-cni#21]
@rparulek , please tag the commits so that the community know which Nuage VSP version a specific commit is compatible with. Does the latest commit work with Nuage VSP 5.1.1?

**Comment by rparulek** [comment]
@greenpau This issue has been addressed.

Latest stable tag which works with Nuage VSP 5.2.1 : https://github.com/nuagenetworks/nuage-cni/tree/v5.2.1-2
